name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello ${{ github.actor }}! :):) !"
      - name: Full Name Greeting
        run: echo "This is your full name ${{ secrets.FIRST_NAME }} ${{ secrets.LAST_NAME }}!!"
  
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: echo "This is a test file created by GitHub Actions Demo" > test-file.txt
      - name: Print File Contents
        run: cat test-file.txt
