name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello ${{ github.actor }}! :):) !"
      - name: Full Name Greeting
        run: echo "This is your full name ${{ secrets.DEPENDABOT_FIRST_NAME }} ${{ secrets.DEPENDABOT_LAST_NAME }}!!"
