name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "Your Full Name"
      - name: my-step
        run: echo "Hello ${{ github.actor }}! :):) !"
