name: hello-world
on: 
  push:
    branches:
      - main
    paths:
      - 'path/to/your/file.txt' # Only trigger on changes to this file

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: echo "This is a test file created by GitHub Actions" > test-file.txt
      - name: Print File Contents
        run: cat test-file.txt

  commit-and-push:
    runs-on: ubuntu-latest
    needs: create-file
    if: github.ref == 'refs/heads/main' && steps.create-file.outputs.file-created == 'true' # Condition to check if file was created
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Commit and Push Changes
        run: |
          git add test-file.txt
          git commit -m "Add test-file.txt"
          git push
